spring.application.name= dice-game
server.port= 8081

### Upstream Configuration
dice.upstream.api.url=http://developer-test.hishab.io/api/v1/roll-dice
dice.upstream.read-time-out=3000
dice.upstream.connection-time-out=3000

### Game configuration
dice.game.winning-score=25