spring.application.name= dice-game
server.port= 8081

### Upstream Configuration
dice.upstream.api.url=http://developer-test.hishab.io/api/v1/roll-dice
dice.upstream.read-time-out=10000
dice.upstream.connection-time-out=10000

### Game Setting
dice.game.start-score=6
dice.game.penalty-score=4
dice.game.winning-score=25